export const colors = {
  primary: '#534AB7',
  primaryDark: '#3f369f',
  success: '#1D9E75',
  error: '#e53e3e',
  white: '#fff',
  black: '#000',
  border: '#eee',
  borderLight: '#f0f0f0',
  borderMid: '#ddd',
  bgPage: '#f8f8f8',
  bgMuted: '#f0f0f0',
  textPrimary: '#111',
  textSecondary: '#555',
  textMuted: '#888',
  textFaint: '#aaa',
  placeholder: '#bbb',
} as const;
